project-id: echo-slam-planetfall
services:
  music-researcher:
    host: localhost:8081
    audience: http://locahost:8081

  youtube-dl-job:
    host: https://youtube-dl-job-twecq3u42q-ew.a.run.app
    location_id: europe-west1
    queue_id: youtube-dl-queue
    subscription_id: youtube-dl-sub

