music-researcher:
  target: music-researcher-twecq3u42q-ew.a.run.app:443

downloader:
  target: https://youtube-dl-job-twecq3u42q-ew.a.run.app/download/url
  location: europe-west1
  queue: youtube-dl-queue
  subscription: youtube-dl-sub
  origins:
    - http://localhost:3000
    - https://dadard.fr
