project-id: echo-slam-planetfall
services:
  music-researcher:
    host: localhost:8080
    audience: https://localhost

  youtube-dl-job:
    host: https://youtube-dl-job-twecq3u42q-ew.a.run.app
    location_id: europe-west1
    queue_id: task1

