project-id: echo-slam-planetfall
services:
  music-researcher:
    host: music-researcher-twecq3u42q-ew.a.run.app:443
    audience: https://music-researcher-twecq3u42q-ew.a.run.ap

  youtube-dl-job:
    host: https://youtube-dl-job-twecq3u42q-ew.a.run.app
    location_id: europe-west1
    queue_id: youtube-dl-queue
    subscription_id: youtube-dl-sub
