// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "No terms",
        "contact": {
            "name": "Support",
            "email": "florian.charpentier67@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "http://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/music-researcher/search": {
            "get": {
                "description": "Searchs for music in Spotify API",
                "consumes": [
                    "application/json"
                ],
                "summary": "Music search",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Main user query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/musicresearcher.Results"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "musicresearcher.Album": {
            "type": "object",
            "properties": {
                "imageUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "releaseDate": {
                    "type": "string"
                },
                "spotifyUrl": {
                    "type": "string"
                }
            }
        },
        "musicresearcher.Artist": {
            "type": "object",
            "properties": {
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "imageUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "spotifyUrl": {
                    "type": "string"
                }
            }
        },
        "musicresearcher.Results": {
            "type": "object",
            "properties": {
                "albums": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/musicresearcher.Album"
                    }
                },
                "artists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/musicresearcher.Artist"
                    }
                },
                "tracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/musicresearcher.Track"
                    }
                }
            }
        },
        "musicresearcher.Track": {
            "type": "object",
            "properties": {
                "album": {
                    "$ref": "#/definitions/musicresearcher.Album"
                },
                "artists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/musicresearcher.Artist"
                    }
                },
                "durationMs": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "popularity": {
                    "type": "integer"
                },
                "previewUrl": {
                    "type": "string"
                },
                "spotifyUrl": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "api.dadard.fr",
	BasePath:         "/",
	Schemes:          []string{"https"},
	Title:            "Gateway Front API",
	Description:      "This application provides a front gateway allowing you\nto interact with multiple GRPC microservices hosted\nin Google Cloud",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
